handlebars:
  suffix: .html
  enabled: true

logging.level.org.hibernate.type.descriptor.sql: trace

spring.jpa.properties.hibernate:
  show_sql: true
  format_sql: true

security.jwt.token:
  secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  expire-length: 3600000

---

spring.profiles.active: test

---

spring:
  config.activate.on-profile: local
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/subway?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: masterpw
  cache.type: redis
  redis:
    host: 172.17.0.1
    prot: 6379

---

spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:mysql://192.168.16.46:3306/subway?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: masterpw
  cache.type: redis
  redis:
    host: 192.168.16.46
    prot: 6379
