version: '3'
services:
  local-db:
    image: brainbackdoor/data-subway:0.0.2
    container_name: local-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      TZ: Asia/Seoul
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
